name: Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build techmino.client.so under linux operating systems.
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    # Setup golang compiler of version Go 1.x
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    # Install the dependencies of pkg-config and luajit.
    - name: Install dependencies
      run: |
        sudo apt update &&
        sudo apt install pkg-config libluajit-5.1-dev

    # Execute checkout to fetch the source code of the project.
    - name: Checkout source code
      uses: actions/checkout@v2

    # Execute build and generate the techmino.client.so lua file.
    - name: Build
      run: GO111MODULE=on GOPROXY=https://goproxy.io go build -buildmode="c-shared" -ldflags "-w -s" -o techmino.client.so -v ./cmd/client

    # Upload the built artifact as the build result.
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
          name: techmino.client-linux.so
          path: techmino.client.so
